version: "3"
services:
  postgresql:
    image: "postgres:10.5-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "postgresqldata:/var/lib/postgresql/data"
    env_file:
      - "variables.env"
volumes:
  postgresqldata: null